//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ingredient.
        /// </summary>
        public static string AddIngredSimple {
            get {
                return ResourceManager.GetString("AddIngredSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountSimple {
            get {
                return ResourceManager.GetString("AmountSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelSimple {
            get {
                return ResourceManager.GetString("CancelSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLangSimple {
            get {
                return ResourceManager.GetString("ChangeLangSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmSimple {
            get {
                return ResourceManager.GetString("ConfirmSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the ingredient &quot;$1&quot;? This operation cannot be undone!.
        /// </summary>
        public static string DelIngredConfirm {
            get {
                return ResourceManager.GetString("DelIngredConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed $1 deletion queries.
        ///Success: $2
        ///Affected rows: $3.
        /// </summary>
        public static string DelQueriesInfo {
            get {
                return ResourceManager.GetString("DelQueriesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the recipe &quot;$1&quot;? This operation cannot be undone!.
        /// </summary>
        public static string DelRecipeConfirm {
            get {
                return ResourceManager.GetString("DelRecipeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorSimple {
            get {
                return ResourceManager.GetString("ErrorSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoSimple {
            get {
                return ResourceManager.GetString("InfoSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new ingredient.
        /// </summary>
        public static string IngredAdd {
            get {
                return ResourceManager.GetString("IngredAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected ingredient.
        /// </summary>
        public static string IngredEdit {
            get {
                return ResourceManager.GetString("IngredEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string IngredientsSimple {
            get {
                return ResourceManager.GetString("IngredientsSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ingredient.
        /// </summary>
        public static string IngredNewSimple {
            get {
                return ResourceManager.GetString("IngredNewSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected ingredient(s).
        /// </summary>
        public static string IngredRemove {
            get {
                return ResourceManager.GetString("IngredRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string IngredSearch {
            get {
                return ResourceManager.GetString("IngredSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ingredient.
        /// </summary>
        public static string IngredUpdateSimple {
            get {
                return ResourceManager.GetString("IngredUpdateSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Ingredients:.
        /// </summary>
        public static string LinkedIngreds {
            get {
                return ResourceManager.GetString("LinkedIngreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed language. Please restart the application for the changes to take effect..
        /// </summary>
        public static string MsgChangedLang {
            get {
                return ResourceManager.GetString("MsgChangedLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find connected database! Some functionality may not work or crash the application..
        /// </summary>
        public static string MsgDBNotFound {
            get {
                return ResourceManager.GetString("MsgDBNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient saved successfully!.
        /// </summary>
        public static string MsgIngredientCreated {
            get {
                return ResourceManager.GetString("MsgIngredientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient could not be fully created! Please edit the database manually if this problem persists..
        /// </summary>
        public static string MsgIngredientCreatedWithErrors {
            get {
                return ResourceManager.GetString("MsgIngredientCreatedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient could not be fully updated! Please edit the database manually if this problem persists..
        /// </summary>
        public static string MsgIngredientUpdatedWithErrors {
            get {
                return ResourceManager.GetString("MsgIngredientUpdatedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of your new ingredient:.
        /// </summary>
        public static string MsgIngredPrompt {
            get {
                return ResourceManager.GetString("MsgIngredPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name of the ingredient:.
        /// </summary>
        public static string MsgIngredPrompt2 {
            get {
                return ResourceManager.GetString("MsgIngredPrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recipe cannot be saved because its content contains illegal characters!
        ///
        ///Illegal characters:
        ///Single quotes
        ///Double quotes.
        /// </summary>
        public static string MsgInvalidRecipeContent {
            get {
                return ResourceManager.GetString("MsgInvalidRecipeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe saved successfully!.
        /// </summary>
        public static string MsgRecipeCreated {
            get {
                return ResourceManager.GetString("MsgRecipeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe could not be fully created! Please edit the database manually and add the remaining data sets ($1 queries failed)..
        /// </summary>
        public static string MsgRecipeCreatedWithErrors {
            get {
                return ResourceManager.GetString("MsgRecipeCreatedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe could not be fully updated! Please edit the database manually and update the remaining data sets ($1 queries failed)..
        /// </summary>
        public static string MsgRecipeUpdatedWithErrors {
            get {
                return ResourceManager.GetString("MsgRecipeUpdatedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameSimple {
            get {
                return ResourceManager.GetString("NameSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recipe.
        /// </summary>
        public static string NewRecipeSimple {
            get {
                return ResourceManager.GetString("NewRecipeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string NoteSimple {
            get {
                return ResourceManager.GetString("NoteSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesSimple {
            get {
                return ResourceManager.GetString("NotesSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsSimple {
            get {
                return ResourceManager.GetString("OptionsSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new recipe.
        /// </summary>
        public static string RecipeCreate {
            get {
                return ResourceManager.GetString("RecipeCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected recipe.
        /// </summary>
        public static string RecipeDelete {
            get {
                return ResourceManager.GetString("RecipeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected recipe.
        /// </summary>
        public static string RecipeEdit {
            get {
                return ResourceManager.GetString("RecipeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipeList {
            get {
                return ResourceManager.GetString("RecipeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Name.
        /// </summary>
        public static string RecipeName {
            get {
                return ResourceManager.GetString("RecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe Preparation.
        /// </summary>
        public static string RecipePrep {
            get {
                return ResourceManager.GetString("RecipePrep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipesSimple {
            get {
                return ResourceManager.GetString("RecipesSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save recipe.
        /// </summary>
        public static string SaveRecipeSimple {
            get {
                return ResourceManager.GetString("SaveRecipeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessSimple {
            get {
                return ResourceManager.GetString("SuccessSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Plan.
        /// </summary>
        public static string WeekPlanSimple {
            get {
                return ResourceManager.GetString("WeekPlanSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeSimple {
            get {
                return ResourceManager.GetString("WelcomeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your personal food planner! Here, you can store all your precious recipes, create a week plan to know what&apos;s for dinner and generate a shopping list based on your week plan to know what to buy for the week..
        /// </summary>
        public static string WelcomeText1 {
            get {
                return ResourceManager.GetString("WelcomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a recipe.
        /// </summary>
        public static string WelcomeText2Btn {
            get {
                return ResourceManager.GetString("WelcomeText2Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to get started right away? Why not .
        /// </summary>
        public static string WelcomeText2Pre {
            get {
                return ResourceManager.GetString("WelcomeText2Pre", resourceCulture);
            }
        }
    }
}
